### ISSUE TITLE
E: Package 'mysql-client' has no installation candidate

### ISSUE THREAD

**Issue by MuriloEduardo** [rmsaitam/project-laravel-docker#2]
Estou tentando rodar `sudo docker-compose build` e esta dando um erro com a mensagem do titulo dessa issue.

-------------------------

No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.4 LTS
Release:	18.04
Codename:	bionic

------------------------

Client:
 Version:           19.03.6
 API version:       1.40
 Go version:        go1.12.17
 Git commit:        369ce74a3c
 Built:             Fri Feb 28 23:45:43 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          19.03.6
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.17
  Git commit:       369ce74a3c
  Built:            Wed Feb 19 01:06:16 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.3.3-0ubuntu1~18.04.1
  GitCommit:        
 runc:
  Version:          spec: 1.0.1-dev
  GitCommit:        
 docker-init:
  Version:          0.18.0
  GitCommit:     

---------------------

docker-compose version 1.23.2, build unknown
docker-py version: 3.7.3
CPython version: 2.7.12
OpenSSL version: OpenSSL 1.0.2g  1 Mar 2016

**Comment by rmsaitam** [comment]
Obrigado por comunicar nessa issue, ajustei o arquivo Dockerfile e demais arquivos de organização.

Faça, o `git pull origin master` para obter as atualizações e depois seguir o Readme.md, ok?

**Comment by MuriloEduardo** [comment]
Muito obrigado, isso resolveu o problema descrito!
